---
title: "Población Activa"
author: "Pablo Catret"
date: "2024-10-26"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library("ggplot2")
library("scales")
library("gganimate")
library("transformr")

if(!require(dplyr)) install.packages("dplyr")
if(!require(tidyr)) install.packages("tidyr")
if(!require(stats)) install.packages("stats")
if(!require(ggplot2)) install.packages("ggplot2")

library(dplyr)
library(tidyr)
library(stats)
library(ggplot2)
library(plotly)
```

## Cargado de datos:

```{r}
url <- "https://www.ine.es/jaxiT3/files/t/es/csv_bdsc/65123.csv?nocab=1"

datos <- read.csv(url, sep=";", dec=",")


datos$Total <- as.numeric(gsub(",", ".", gsub("\\.", "", datos$Total)))

sacarFechas <- function(x) {
  año <- as.numeric(substr(x, 1, 4))
  trimestre <- substr(x, 6, 6)
  mes <- switch(trimestre, "1" = "03", "2" = "06", "3" = "09", "4" = "12")
  paste(año, mes, "01", sep = "-")
}

datos$Fecha <- as.Date(sapply(datos$Periodo, sacarFechas), format = "%Y-%m-%d")

datos_porc <- datos[datos$Unidad=="Porcentaje",]
datos_porc <- datos_porc[, !names(datos_porc) %in% "Unidad"]

datos_abs <- datos[datos$Unidad=="Valor absoluto",]
datos_abs <- datos_abs[, !names(datos_abs) %in% "Unidad"]
datos_abs$Total <- datos_abs$Total *1000
datos_abs <- datos_abs[order(datos_abs$Fecha), ]

datos_abs$Diferencia_Total <- NA

for (sexo in unique(datos_abs$Sexo)) {
  for (rama in unique(datos_abs$Rama.de.actividad.CNAE.2009)) {
    subset <- datos_abs[datos_abs$Sexo == sexo & 
                        datos_abs$Rama.de.actividad.CNAE.2009 == rama, ]
    
    datos_abs$Diferencia_Total[datos_abs$Sexo == sexo & 
                                datos_abs$Rama.de.actividad.CNAE.2009 == rama] <- 
      c(NA, diff(subset$Total))
  }
}

```


## Representación de datos

```{r}
fin_crisis <- as.Date("2013-06-01")      # Fin de la crisis (junio 2013)
inicio_covid <- as.Date("2020-03-01")    # Inicio de COVID (marzo 2020)

ggplot(datos_abs[datos_abs$Sexo != "Total" & datos_abs$Rama.de.actividad.CNAE.2009 == "Total", ], 
       aes(x = Fecha, y = Total, color = Sexo, group = Sexo)) +
  
  geom_line() + 
  geom_point() +
  
  geom_vline(xintercept = as.numeric(fin_crisis), linetype = "dashed", color = "grey30", size = 0.5) +
  geom_vline(xintercept = as.numeric(inicio_covid), linetype = "dashed", color = "grey30", size = 0.5) +
  geom_text(aes(x = fin_crisis, y = max(datos_abs$Total, na.rm = TRUE) * 0.6,
                label = "Fin de la crisis\n (2013)"), 
                color = "grey30", size = 3, fontface = "italic",
            hjust = -0.04, vjust = 0) +
  geom_text(aes(x = inicio_covid, y = max(datos_abs$Total, na.rm = TRUE) * 0.6,
                label = "Inicio COVID\n (2020)" 
                ), color = "grey30", size = 3,fontface = "italic",
            hjust = -0.04, vjust = 0) +
  
  scale_y_continuous(labels = label_number(big.mark = ","), expand = expansion(mult = c(0, 0.05))) +
  
  expand_limits(y = 0) +
  
  theme_minimal() +
  
  labs(title = "Evolución del empleo en España",
       x = "Fecha",
       y = "Total")

```

```{r}
ggplot(datos_abs[datos_abs$Sexo != "Total" & datos_abs$Rama.de.actividad.CNAE.2009 == "Total", ], 
       aes(x = Fecha, y = Diferencia_Total, color = Sexo, group = Sexo)) +
  
  geom_line() + 
  geom_point() +
  
  geom_vline(xintercept = as.numeric(fin_crisis), linetype = "dashed", color = "grey30", size = 0.5) +
  geom_vline(xintercept = as.numeric(inicio_covid), linetype = "dashed", color = "grey30", size = 0.5) +
  
  geom_text(aes(x = fin_crisis, y = -750000,
                label = "Fin de la crisis\n (2013)"), 
            color = "grey30", size = 3, fontface = "italic",
            hjust = -0.04, vjust = 0) +
  geom_text(aes(x = inicio_covid, y = -750000,
                label = "Inicio COVID\n (2020)" 
                ), color = "grey30", size = 3, fontface = "italic",
            hjust = -0.04, vjust = 0) +
  
  scale_y_continuous(labels = label_number(big.mark = ","), expand = expansion(mult = c(0, 0.05))) +
  
  theme_minimal() +
  
  labs(title = "Evolución del empleo en España (Diferencia respecto al periodo anterior)",
       x = "Fecha",
       y = "Diferencia en Total")
```

## Datos normalizados
```{r}
library(dplyr)

data_normalized <- datos_abs[datos_abs$Sexo=="Ambos sexos",] %>%
  group_by(Rama.de.actividad.CNAE.2009) %>%
  arrange(Fecha) %>%  # Ordena por fecha dentro de cada grupo
  mutate(Primer_Total = first(Total),  # Obtiene el primer valor de Total
         Total_Normalizado = Total / Primer_Total) %>%  # Normaliza dividiendo por el primer valor
  ungroup()  # Desagrupa al final

```

## 

```{r}
data_wide <- data_normalized %>%
  select(Rama.de.actividad.CNAE.2009, Fecha, Total_Normalizado) %>%  # Seleccionar las columnas necesarias
  pivot_wider(names_from = Fecha, values_from = Total_Normalizado, values_fill = 0)
data_wide <- na.omit(data_wide)

diferencias <- data_wide %>%
  select(-Rama.de.actividad.CNAE.2009) %>%  # Excluir la columna de Rama
  as.matrix() 

distancias_matriz <- dist(diferencias, method = "euclidean")

distancias_matriz <- as.matrix(distancias_matriz)

rownames(distancias_matriz) <- data_wide$Rama.de.actividad.CNAE.2009
colnames(distancias_matriz) <- data_wide$Rama.de.actividad.CNAE.2009

mds_result <- cmdscale(distancias_matriz, k = 2)

mds_data <- as.data.frame(mds_result)

nombres_actividades <- colnames(distancias_matriz)

mds_data$Rama <- nombres_actividades

grafica_mds <- ggplot(mds_data, aes(x = V1, y = V2, label = Rama)) +
  geom_point(color = "blue") +
  labs(title = "Proyección MDS de actividades por medias de diferencias entre datos normalizados",
       x = "Dimensión 1", y = "Dimensión 2") +
  theme_minimal()
grafica_interactiva <- ggplotly(grafica_mds)

grafica_interactiva
```

Observamos los outliers:
```{r}
ggplot(datos_abs[datos_abs$Rama.de.actividad.CNAE.2009=="99 Actividades de organizaciones y organismos extraterritoriales",], aes(x=Fecha,y=Total, color=Sexo))+geom_line()
ggplot(datos_abs[datos_abs$Rama.de.actividad.CNAE.2009=="07 Extracción de minerales metálicos",], aes(x=Fecha,y=Total, color=Sexo))+geom_line()
ggplot(datos_abs[datos_abs$Rama.de.actividad.CNAE.2009=="Total",], aes(x=Fecha,y=Total, color=Sexo))+geom_line()
```
## Clusterización y proyección

```{r}
set.seed(123)
num_clusters <- 5
clusters <- kmeans(diferencias, centers = num_clusters)

mds_data$Cluster <- as.factor(clusters$cluster)
grafica_mds <- ggplot(mds_data, aes(x = V1, y = V2, color = Cluster, label = Rama)) +
  geom_point(size = 2, alpha=0.8) +
  labs(title = "Proyección MDS de actividades por medias de diferencias entre datos normalizados",
       x = "Dimensión 1", y = "Dimensión 2") +
  theme_minimal()

grafica_interactiva <- ggplotly(grafica_mds)

grafica_interactiva
```

```{r}
medias_por_cluster <- data_wide %>%
  group_by(Cluster = mds_data$Cluster) %>%
  summarise(across(everything(), mean, na.rm = TRUE)) %>% 
  pivot_longer(-c(Cluster,Rama.de.actividad.CNAE.2009), names_to = "Fecha", values_to = "Media")

grafico_lineas <- ggplot(medias_por_cluster, aes(x = Fecha, y = 100*Media, color = Cluster, group = Cluster)) +
  geom_line(size = 1) +
  geom_point(size = 2) +
  labs(title = "Media de Total Normalizado por Cluster a lo Largo del Tiempo",
       x = "Fecha", y = "Media de Total Normalizado") +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))

print(grafico_lineas)
```

```{r}
data_wide$Cluster <- as.factor(mds_data$Cluster)

data_long <- data_wide %>%
  pivot_longer(-c(Rama.de.actividad.CNAE.2009, Cluster), names_to = "Fecha", values_to = "Total_Normalizado")

cuantiles_por_cluster <- data_long %>%
  group_by(Cluster, Fecha) %>%
  summarise(
    Cuantil_25 = quantile(Total_Normalizado, 0.25, na.rm = TRUE),
    Cuantil_50 = quantile(Total_Normalizado, 0.50, na.rm = TRUE),
    Cuantil_75 = quantile(Total_Normalizado, 0.75, na.rm = TRUE),
    .groups = 'drop'
  ) %>%
  pivot_longer(-c(Cluster, Fecha), names_to = "Cuantil", values_to = "Valor")

grafico_cuantiles <- ggplot(cuantiles_por_cluster, aes(x = Fecha, y = Valor, color = Cluster, group = interaction(Cluster, Cuantil))) +
  geom_line(size = 1) +
  geom_point(size = 2) +
  facet_wrap(~ Cuantil, nrow = 3, scales = "free_y") + 
  labs(title = "Cuantiles de Total Normalizado por Cluster a lo Largo del Tiempo",
       x = "Fecha", y = "Valor") +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) 

print(grafico_cuantiles)
```

